### ISSUE TITLE
Feature:  Add tree shakeable component example

### ISSUE THREAD

**Issue by blowsie** [jacobclevenger/vaguer#1]
Thank you for this example!

Could you please consider adding an example that allows TreeShakable usage?
Something like
```js
import { VaguerButton } from 'VaguerComponents'
```

For this to work efficiently, perhaps the css should be kept with the component too?

**Comment by wheatjs** [comment]
Thanks for the suggestion!

The project now includes a script that will add tree-shakeable exports for each component. As for CSS I don't know if that is possible. Since the library is compiled into javascript, the css would have to be extracted. One option would be to have the end-user have a css purge tool that can purge unused styles.
